parameters:
#    recibos.example.class: DSNEmpresas\Recibos\RecibosBundle\Example

services:
#    recibos.example:
#        class: %recibos.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
