parameters:
#    ciudades.example.class: DSNEmpresas\Ciudades\CiudadesBundle\Example

services:
#    ciudades.example:
#        class: %ciudades.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
