parameters:
#    comisiones.example.class: DSNEmpresas\Comisiones\ComisionesBundle\Example

services:
#    comisiones.example:
#        class: %comisiones.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
