MediterraneoFM\MediterraneoFMBundle\Entity\liquidacionesMovimientos:
    type: entity
    table: liquidaciones_movimientos
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        porcentaje:
            type: float
        importeBase:
            type: float
            column: importe_base
    manyToOne:
        idOrdenpub:
            targetEntity: DSNEmpresas\OrdenPub\OrdenPubBundle\Entity\OrdenPub
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_ordenpub:
                    referencedColumnName: id_ordenpub
            orphanRemoval: false
        idLiquidacion:
            targetEntity: DSNEmpresas\CtasCtesAgencias\CtasCtesAgenciasBundle\Entity\Liquidaciones
            cascade: { }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_liquidacion:
                    referencedColumnName: id
                    onDelete: CASCADE
                    # al eliminar la liquidación queremos que se eliminen todos los movimientos de esta liquidacion
            orphanRemoval: false
    lifecycleCallbacks: {  }
