DSNEmpresas\OrdenPub\OrdenPubBundle\Entity\ordenesAnuladas:
    type: entity
    table: ordenes_anuladas
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        motivoAnula:
            type: string
            length: 255
            column: motivo_anula
    manyToOne:
        idOrdenPub:
            targetEntity: DSNEmpresas\OrdenPub\OrdenPubBundle\Entity\OrdenPub
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idOrdenPub:
                    referencedColumnName: id_ordenpub
                    onDelete: CASCADE
                    # El motivo de la anulacion de una orden al eliminarla ya no es importante. Por lo que lo eliminamos tambien
            orphanRemoval: false
    lifecycleCallbacks: {  }
