DSNEmpresas\Recibos\RecibosBundle\Entity\Recibos:
    type: entity
    table: Recibos
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nro_recibo:
            type: integer
            unsigned: false
            nullable: false
            column: nro_recibo
        fecha:
            type: date
            nullable: false
        importe:
            type: string
            length: 255
            fixed: false
            nullable: false
        concepto:
            type: string
            length: 255
            fixed: false
            nullable: true
        total:
            type: float
            unsigned: false
            nullable: false
    manyToOne:
        idOrdenPub:
            targetEntity: DSNEmpresas\OrdenPub\OrdenPubBundle\Entity\OrdenPub
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idOrdenPub:
                    referencedColumnName: id_ordenpub
            orphanRemoval: false
    lifecycleCallbacks: {  }
