parameters:
#    clientes.example.class: DSNEmpresas\Clientes\ClientesBundle\Example

services:
#    clientes.example:
#        class: %clientes.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
